Repository newrelic/node-native-metrics, pull requests merged in 2020-08, with the labels that each got.

#98 update ci workflow
  .github/workflows/ci-workflow.yml
  .github/workflows/linux-ci-workflow.yml
  .github/workflows/windows-ci-workflow.yml
Labels: risk:none, semver:patch

#99 License
  LICENSE
  bin/test-all-node.sh
  lib/pre-build.js
  src/GCBinder.cpp
  src/GCBinder.hpp
  src/LoopChecker.cpp
  src/LoopChecker.hpp
  src/Metric.hpp
  src/RUsageMeter.cpp
  src/RUsageMeter.hpp
  src/native_metrics.cpp
  src/tests/main.cpp
  src/tests/metrics_test.cpp
  tests/integration/loop-performance.tap.js
  tests/integration/server.tap.js
  tests/native/run.js
  tests/unit/gc-metrics.tap.js
  tests/unit/licenses.tap.js
  tests/unit/loop-metrics.tap.js
  tests/unit/ru-meter.tap.js
Labels: ready for review

#100 Adds pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: risk:low, semver:patch

#102 Updates contributing guide
  CONTRIBUTING.md
Labels: risk:low, semver:patch

#101 Adds code of conduct
  CODE_OF_CONDUCT.md
Labels: risk:low, semver:patch

#105 Add release workflow
  .github/workflows/release-workflow.yml
Labels: ready for review, risk:low, semver:patch

#104 Update third party notices and manifest
  THIRD_PARTY_NOTICES.md
  third_party_manifest.json
Labels: risk:none, semver:patch

#103 Updates readme to match current standards and adds additional info.
  README.md
Labels: risk:low, semver:patch

#106 Merge OS main into main
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci-workflow.yml
  .github/workflows/release-workflow.yml
  .travis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  THIRD_PARTY_NOTICES.md
  appveyor.yml
  bin/test-all-node.sh
  lib/pre-build.js
  src/GCBinder.cpp
  src/GCBinder.hpp
  src/LoopChecker.cpp
  src/LoopChecker.hpp
  src/Metric.hpp
  src/RUsageMeter.cpp
  src/RUsageMeter.hpp
  src/native_metrics.cpp
  src/tests/main.cpp
  src/tests/metrics_test.cpp
  tests/integration/loop-performance.tap.js
  tests/integration/server.tap.js
  tests/native/run.js
  tests/unit/gc-metrics.tap.js
  tests/unit/licenses.tap.js
  tests/unit/loop-metrics.tap.js
  tests/unit/ru-meter.tap.js
  third_party_manifest.json
Labels: risk:low, semver:minor

#107 Adds additional npmignore items.
  .npmignore
Labels: risk:low, semver:patch

#108 Fixes license ref in package.json.
  package.json
Labels: risk:low, semver:patch

#109 Release v5.3.0
  CHANGELOG.md
Labels: risk:low, semver:minor

#110 Changes release ci/job names. Filters out tags for main CI job.
  .github/workflows/ci-workflow.yml
  .github/workflows/release-workflow.yml
Labels: risk:low, semver:patch

#111 Fixes license formatting.
  LICENSE
Labels: risk:low, semver:patch
