Repository newrelic/node-native-metrics, pull requests merged in 2021-07, with the labels that each got.

#129 Adds Node 16 to CI.
  .github/workflows/ci-workflow.yml
Labels: risk:low, semver:patch

#140 Release v7.0.0
  CHANGELOG.md
Labels: risk:low, semver:major

#143 Release v7.0.1
  CHANGELOG.md
Labels: risk:low, semver:patch

#144 release/v7.0.1 addendum
  CHANGELOG.md
  package.json
Labels: risk:medium, semver:patch
